# Notes: leading dashes set off items in an ordered list.
# Indentation is done with spaces. It determines the scope of some items.

Step Order:
  # Format:
  # - "widget_name"
  # - ...
  - "reformat_dates_to_gtnp"
  - "remove_characters"
  - "divide_constant"
  - "replace_less_than"

Step Definitions:
  # The order in this list needs to match the `Step Order` above. 
  # Format:
  # -
  #   widget: "Widget name"
  #   input columns: ["col1", "col2"]
  #   output columns: ["col1", "col2"]
  #   inputs:
  #     - port1: data1
  #     - port2: data2
  #     - ...
  # -
  #   Another widget definition
  -
    widget: "reformat_dates_to_gtnp"
    input columns: ["date:time"]
    inputs:
      - format: "'%Y%m%dT%H%M'"
    output columns: ["Date/Time"]
  -
    widget: "remove_characters"
    input columns: ["Depth"]
    inputs:
      - characters: ["_CMAB"]
    output columns: ["Depth"]
  -
    widget: "divide_constant"
    input columns: ["Depth"]
    inputs:
      - constant: 100
    output columns: ["Depth"]
  -
    widget: "replace_less_than"
    input columns: ["Temperature"]
    output columns: ["Temperature"]
    inputs:
      - threshold: -200
      - value: -999.0

Files:
  # Format:
  # - "path/to/file"
  - "./Example_data/AKUL232"
  - "./Example_data/AUPA299"

Variable map file:
  - "./Example_data/variable_map.dat"



Missing Values:  # Currently unused
  -999
  "na"

