Step Order:
  - "remove_characters"
  - "divide_constant"

Step Definitions:
  # Format:
  # "Step being defined":
  #   widget: "Widget name"
  #   columns:
  #     - "column 1 name"
  #     - "column 2 name"
  #     - ...
  #   args:
  #     - port1: data1
  #     - port2: data2
  #     - ...
  # -
  #   Another widget definition
  -
    widget: "remove_characters"
    input columns: ["Depth", "Temperature"]
    inputs:
      - characters: "_CM"
    output columns: ["Depth", "Temperature"]
  -
    widget: "divide_constant"
    input columns: ["Depth"]
    inputs:
      - constant: 100
    output columns: ["Depth"]

Missing Values:
  -999
  "na"


Files:
  # Format:
  # -
  #   filename: path to data file
  - "/data/raw_files/AKUL232"
  - "/data/raw_files/AUPA299"


Variable map file:
  "variable_map.dat"

# Variable map:
#   # -
#   #   input header: "name"
#   #   output header: "name"; this plus units will become the header of the column in the output file
#   #   operation: "copy", "change", "create", or "remove"
#   #   input column: an integer or "null"
#   #   output column: an integer or "null"
#   #   units: "m", "degrees C", etc.
#   #   description: a couple words to tell you what it is
#   # -
#   #   More variable definitions
#   -
#     input header: "Station"
#     output header: "Station"
#     operation: "copy"
#     input column: 1
#     output column: 1
#     units: ""
#     description: "Station ID"
#   -
#     input header: "qc"
#     output header: "Quality Code"
#     operation: "remove"
#     input column: 3
#     output column: "null"
#     units: ""
#     description: "Quality control code"
#   -
#     input header: "Depth"
#     operation: "copy"
#     input column: 4
#     output column: 3
#     units: "m"
#     description: "Depth of measurement"
